%Author: Kiarie Ndegwa u4742829
%Assignment 1 comp8420: Multi-layer and cascade neural networks for
%the classification of Diabete Mellitus.

%This project works on classifying different liver disorders based
%on a small data set comprised of 768 entries

%The paper accompanying the data set achieved a classification accuracy 76%.
clear
clc
%Keep the random seed the same during all network initialization during
%testing
rng('default')
DiabetesData = csvread('IndianDiabetesData.csv');

%Divide the data set into input attributes and binary outputs
inputs = DiabetesData(:, 1:end-1)';
outputs = DiabetesData(:, end)';

%Data pre-processing
%-----------------------------------------------------------------%
%STEP 1: PCA dimension reduction

%Step skipped as PCA doesn't reduce the dimensionality of the input
%PCA = pca(inputs);

%STEP 2: Scale inputs between -1 and 1
ProcInputs = bsxfun(@minus, inputs, mean(inputs));
%STEP 3: Normalize the PCA components.
ProcInputs = normc(ProcInputs);
%----------------------------------------------------------------%

%Create validation indices with 10 fold cross validation
%----------------------------------------------------------------%
CVO = cvpartition(outputs(1, :), 'k', 10);

%These vectors keeps record of the test error on unprocessed data
errCascProc = zeros(CVO.NumTestSets,1);
%---------------------------------------------------------------%
%This trains the cascade net on processed data
for i = 1:CVO.NumTestSets
     trIdxProc = CVO.training(i);
     teIdxProc = CVO.test(i);
     train_inputsProc= ProcInputs(:,trIdxProc);
     train_outputsProc= outputs(:,trIdxProc);
     test_inputsProc= ProcInputs(:,teIdxProc);
     test_outputsProc= outputs(:,teIdxProc);
     %A cascade network generated by the cascase function
     netCascProc = cascadeforwardnet([4, 2]);
     netCascProc = train(netCascProc, train_inputsProc, train_outputsProc);
     %Test network on input data   
     y_netCascProc = netCascProc(test_inputsProc);
     errCascProc(i) = sum(round(y_netCascProc)~=test_outputsProc)/length(test_outputsProc);
end

%Find accuracy of trained networks
errCascProc = sum(errCascProc)/CVO.NumTestSets;

%Display results in the console
X = sprintf('Classification accuracy on unprocessed input data for Cascade network %.2f%%',(1-errCascProc)*100);
disp(X);
